import  pandas as pd
import numpy as np


df = pd.read_csv('../House_Rent_Dhaka_with_Categorical_to_AreaCode.csv')

location_set = set(df['Location'])

for i in list(location_set):
    print(f"'{i}',", end=' \n')


location_set_list = ['2nd Colony, Mirpur, Dhaka',
'Block D, Bashundhara R-A, Dhaka',
'Block J, Pallabi Extension, Pallabi, Mirpur, Dhaka', 
'Ullan, Rampura, Dhaka',
'Green City Housing, Mohammadpur, Dhaka',
'Kulutala, Sutrapur, Dhaka',
'Tajmahal Road, Mohammadpur, Dhaka',
'Goaltek, Dakshin Khan, Dhaka',
'Road No 16, Banani, Dhaka',
'Akota Residential Area, Uttar Badda, Badda, Dhaka',
'Kadamtala, Bashabo, Dhaka',
'Avenue 12, Mirpur DOHS, Mirpur, Dhaka',
'Block C, Mohanagar Housing, West Rampura, Rampura, Dhaka',
'Eskaton, Dhaka',
'Block B, Section 2, Mirpur, Dhaka',
'Ullan, West Rampura, Rampura, Dhaka',
'Sonatangar, Jigatola, Hazaribag, Dhaka',
'Block B, Chandrima Model Town, Mohammadpur, Dhaka',
'Shahjadpur, Badda, Dhaka',
'Sector 10, Uttara, Dhaka',
'Block L, South Banasree Project, Banasree, Dhaka',
'Block A, Metro Housing, Bochila, Mohammadpur, Dhaka',
'Block C, Section 1, Mirpur, Dhaka',
'Transmitter, Faydabad, Dakshin Khan, Dhaka',
'Mansurabad Housing Society, Adabor, Dhaka',
'Block C, Section 11, Mirpur, Dhaka',
'Block D, Pallabi, Mirpur, Dhaka',
'Paikpara, Mirpur, Dhaka',
'Kalabagan, Dhaka',
'Tilpapara, Khilgaon, Dhaka',
'Sector 1, Block F, Aftab Nagar, Dhaka',
'Karwan Bazar, Tejgaon, Dhaka',
'Abdur Rafique Housing Society, Shekhertek, Mohammadpur, Dhaka',
'Chandrima Model Town, Mohammadpur, Dhaka',
'Hashem Khan Road, Sultanganj, Rayer Bazaar, Hazaribag, Dhaka',
'Meradia, Khilgaon, Dhaka',
'Block A, Arifabad Housing Society, Pallabi, Mirpur, Dhaka',
'Block D, Eastern Housing, Pallabi, Mirpur, Dhaka',
'East Monipur, Mirpur, Dhaka',
'Kakrail, Dhaka',
'North Gawair, Gawair, Dakshin Khan, Dhaka',
'Tejturi Bazar, Tejgaon, Dhaka',
'Block F, Section 2, Mirpur, Dhaka',
'Kamal Sarani, South Pirerbag, Pirerbag, Mirpur, Dhaka',
'Hazaribag, Dhaka',
'Block B, Kaderabad Housing Society, Katashur, Mohammadpur, Dhaka',
'Block E, Arambag Residential Area, Pallabi, Mirpur, Dhaka',
'Rupali Housing, Section 3, Mirpur, Dhaka',
'South Monipur, Mirpur, Dhaka',
'Dakkhin Paikpara, Paikpara, Mirpur, Dhaka',
'Senpara Parbata, Section 10, Mirpur, Dhaka',
'East Khilbari Tek, Khilbari Tek, Badda, Dhaka',
'Sabujbag, South Bashabo, Bashabo, Dhaka',
'Shahbagh, Dhaka',
'Madani Avenue, Natun Bazar, Badda, Dhaka',
'Donia, Jatra Bari, Dhaka',
'Uttar Namapara, Namapara, Khilkhet, Dhaka',
'North Pirerbag, Pirerbag, Mirpur, Dhaka',
'Block A, Section 10, Mirpur, Dhaka',
'Adabor, Dhaka',
'Borobag, Section 2, Mirpur, Dhaka',
'Kawlar Moddho Para, Kawlar, Dakshin Khan, Dhaka',
'Block H, Kazi Furi, Ghudaraghat, Section 1, Mirpur, Dhaka',
'Block C, Section 12, Mirpur, Dhaka',
'Sector 1, Block G, Aftab Nagar, Dhaka',
'Middle Faydabad, Faydabad, Dakshin Khan, Dhaka',
'Mayakanon, Sabujbag, South Bashabo, Bashabo, Dhaka',
'Mohammadpur, Dhaka',
'East Maniknagar, Maniknagar, Dhaka',
'West Dhanmondi, Dhanmondi, Dhaka',
'Block D, Section 1, Mirpur, Dhaka',
'Dolipara, Uttara, Dhaka',
'Eastern Housing, Pallabi, Mirpur, Dhaka',
'North Goran, Khilgaon, Goran, Khilgaon, Dhaka',
'Block E, Banasree, Dhaka',
'Block C, Metro Housing, Bochila, Mohammadpur, Dhaka',
'Block C, Chad Uddan Housing, Mohammadpur, Dhaka',
'Road No 1, West Nandipara, Khilgaon, Dhaka',
'North Donia, Donia, Jatra Bari, Dhaka',
'Bakshi Bazar, Lalbagh, Dhaka',
'Block C, Section 6, Mirpur, Dhaka',
'Rajarbagh, Motijheel, Dhaka',
'Block D, Nobodoy Housing Society, Mohammadpur, Dhaka',
'Kutubkhali, Jatra Bari, Dhaka',
'Avenue 8, Mirpur DOHS, Mirpur, Dhaka',
'Block D, Chad Uddan Housing, Mohammadpur, Dhaka',
'Lalbagh Road, Lalbagh, Dhaka',
'Block C, Section 2, Mirpur, Dhaka',
'PC Culture Housing Society, Shyamoli, Dhaka',
'Block B, Mansurabad Housing Society, Adabor, Dhaka',
'Modhubag, Boro Maghbazar, Maghbazar, Dhaka',
'West Pirerbag, Pirerbag, Mirpur, Dhaka',
'Block A, Sayednagar, East Vatara, Vatara, Badda, Dhaka',
'Merul Badda, Badda, Dhaka',
'Mastertek, Cantonment, Dhaka',
'Porod Diea, Satarkul, Uttar Badda, Badda, Dhaka',
'Sector 12, Uttara, Dhaka',
'Rampura, Dhaka',
'Dakshin Khan, Dhaka',
'Sepahibag, North Goran, Khilgaon, Dhaka-1219, Goran, Khilgaon, Dhaka',
'Block D, Future Town, Bochila, Mohammadpur, Dhaka',
'Kotwali, Dhaka',
'Block C, Section 13, Mirpur, Dhaka',
'Rayer Bazaar, Hazaribag, Dhaka',
'Jhigatola Road, Dhanmondi, Dhaka',
'Fakirapool, Motijheel, Dhaka',
'Block A, Mansurabad Housing Society, Adabor, Dhaka',
'West Meradia, Meradia, Khilgaon, Dhaka',
'Sector 2, Block E, Aftab Nagar, Dhaka',
'Block C, Khilgaon, Dhaka',
'Mirpur Road, New Market, Dhaka',
'South Bashabo, Bashabo, Dhaka',
'North Bashabo, Bashabo, Dhaka',
'Block A, South Banasree Project, Banasree, Dhaka',
'Block B, Bochila Garden City, Bochila, Mohammadpur, Dhaka',
'Avenue 3, Block A, Section 11, Mirpur, Dhaka', 
'Block A, Chandmiya Housing, Mohammadpur, Dhaka',
'Janata Housing Society, Adabor, Dhaka',
'Jamtola, East Rampura, Rampura, Dhaka',
'Block H, Bashundhara R-A, Dhaka',
'West Nandipara, Khilgaon, Dhaka',
'Block B, Section 13, Mirpur, Dhaka',
'South Kutubkhali, Kutubkhali, Jatra Bari, Dhaka',
'West Agargaon, Agargaon, Dhaka',
'Avenue 2, Block C, Section 13, Mirpur, Dhaka',
'Block J, South Banasree Project, Banasree, Dhaka',
'Bashabo, Dhaka',
'Polashpur, East Doniya, Doniya, Shyampur, Dhaka',
'Block D, Dakkhin Paikpara, Paikpara, Mirpur, Dhaka',
'Block E, Section 1, Mirpur, Dhaka',
'East Ahmed Nagar, Ahmed Nagar, Mirpur, Dhaka',
'Tali office Road, Hazaribag, Dhaka',
'Avenue 1, Mirpur DOHS, Mirpur, Dhaka',
'Block E, Section 11, Mirpur, Dhaka',
'Sector 14, Uttara, Dhaka',
'Moushair, Dakshin Khan, Dhaka',
'Darussalam, Mirpur, Dhaka',
'South Banasree Project, Banasree, Dhaka',
'Block C, Bochila City Developers Ltd, Bochila, Mohammadpur, Dhaka',
'Block B, Mohammadi Homes R/A, Mohammadpur, Dhaka',
'East Namapara, Namapara, Khilkhet, Dhaka',
'Block B, Banasree, Dhaka',
'Block C, Niketan, Dhaka',
'Golapbag, Jatra Bari, Dhaka',
'Block D Extension, Banasree, Dhaka',
'Middle Kuril, Kuril, Dhaka',
'Dogair, Demra, Dhaka',
'Rasulpur, Donia, Jatra Bari, Dhaka',
'Tati Bazaar, Kotwali, Dhaka',
'Mukti Polli, Khilbari Tek, Badda, Dhaka',
'Paikpara, Ahmed Nagar, Mirpur, Dhaka',
'Swapnodhara Housing, Bochila, Mohammadpur, Dhaka',
'South Pirerbag, Pirerbag, Mirpur, Dhaka',
'Bosila, Mohammadpur, Dhaka',
'Block C, Dhaka Uddan, Mohammadpur, Dhaka',
'Khaje Dewan, Lalbagh, Dhaka',
'Turag Housing, Mohammadpur, Dhaka',
'South Pirerbag, Pirerbag, Section 1, Mirpur, Dhaka',
'Chayabithi Eastern Housing, Middle Bashabo, Bashabo, Dhaka',
'Block C, Mansurabad Housing Society, Adabor, Dhaka',
'South Shahjahanpur, Shahjahanpur, Dhaka',
'Block B, Dhaka Uddan, Mohammadpur, Dhaka',
'Khilkhet, Dhaka',
'Pakar Matha, East Shewrapara, Mirpur, Dhaka',
'Block B, Sayednagar, East Vatara, Vatara, Badda, Dhaka',
'Block G, Banasree, Dhaka',
'East Badda, Badda, Dhaka',
'Bashundhara R-A, Dhaka',
'Block B, Aftab Nagar, Dhaka',
'Avenue 2, Section 11, Mirpur, Dhaka',
'Mirpur DOHS, Mirpur, Dhaka',
'Indira Road, Tejgaon, Dhaka',
'Block A, Bochila West Dhanmondi R/A, Bochila, Mohammadpur, Dhaka',
'2nd Lane, Gopibag, Motijheel, Dhaka',
'Gulshan 2, Gulshan, Dhaka',
'Block C, Aftab Nagar, Dhaka',
'Mollika R/A, Section 7, Mirpur, Dhaka',
'Block TA, Section 12, Mirpur, Dhaka',
'Nazimuddin Road, Saat Rawza, Bangshal, Dhaka',
'Kazirgaon, Jatra Bari, Dhaka',
'Ring Road, Shyamoli, Dhaka',
'Avenue 11, Mirpur DOHS, Mirpur, Dhaka',
'Kamal Soroni, Middle Pirerbag, Pirerbag, Mirpur, Dhaka',
'Nowapara, Dakshin Khan, Dhaka',
'Nadda, Dhaka',
'Ward 23, Chowdhuripara, Khilgaon, Dhaka',
'Block D, Bochila Garden City, Bochila, Mohammadpur, Dhaka',
'West Nakhalpara, Tejgaon, Dhaka',
'Shimulbag, West Rampura, Rampura, Dhaka',
'Purana Polton Lane, Purana Paltan, Motijheel, Dhaka',
'Block Kha, North Bishil, Section 1, Mirpur, Dhaka',
'Block Dha, Section 12, Mirpur, Dhaka',
'Banani, Dhaka', 
'PC Culture Housing, Mohammadpur, Dhaka',
'West Mollartek, Dakshin Khan, Dhaka',
'Madhya Ajampur, Dakshin Khan, Dhaka',
'Nabi Nagar Housing, Mohammadpur, Dhaka', 
'Barontek, Cantonment, Dhaka', 
'Armanitola, Naya Bazar, Bangshal, Dhaka',
'Rajarbag, Bashabo, Dhaka',
'West Malibag, Malibagh, Dhaka',
'Block E, Bashundhara R-A, Dhaka',
'Block B, Section 12, Mirpur, Dhaka',
'Sankar, Hazaribag, Dhaka',
'Sector 2, Block H, Aftab Nagar, Dhaka',
'Tikatuli, Sutrapur, Dhaka',
'Gulshan 1, Gulshan, Dhaka',
'Kallyanpur, Mirpur, Dhaka',
'Block D, Aftab Nagar, Dhaka',
'Goran, Khilgaon, Dhaka',
'Block A, Bochila City Developers Ltd, Bochila, Mohammadpur, Dhaka',
'Khilbari Tek, Badda, Dhaka',
'Mir Hajirbag, Jatra Bari, Dhaka',
'Ibrahimpur, Dhaka',
'Sheikhdi, Jatra Bari, Dhaka',
'East Merul Badda, Merul Badda, Badda, Dhaka',
'Zafrabad, Hazaribag, Dhaka',
'IBN SINA Housing, Adabor, Dhaka',
'East Goran, Goran, Khilgaon, Dhaka',
'Chawk Bazar, Lalbagh, Dhaka',
'Jagannathpur, Badda, Dhaka',
'Taltola, Dhaka',
'Bangshal, Dhaka',
'Pilkhana, Hazaribag, Dhaka',
'Ashkona, Dakshin Khan, Dhaka',
'Sikder Real Estate, Tali office Road, Hazaribag, Dhaka',
'Block F, Section 1, Mirpur, Dhaka',
'Sayednagar, East Vatara, Vatara, Badda, Dhaka',
'East Mollartek, Dakshin Khan, Dhaka',
'Block F, Eastern Housing, Pallabi, Mirpur, Dhaka',
'Duip R-A, Block B, Section 2, Mirpur, Dhaka',
'Block D, Arambag Residential Area, Pallabi, Mirpur, Dhaka',
'Nawabgonj, Lalbagh, Dhaka',
'Eastern Pallabi, Pallabi, Mirpur, Dhaka',
'Shyamoli Housing, Shekhertek, Mohammadpur, Dhaka',
'Lalmatia, Dhaka',
'Jashimuddin Avenue, Dolipara, Uttara, Dhaka',
'Sultanganj, Rayer Bazaar, Hazaribag, Dhaka',
'South Kallyanpur, Kallyanpur, Mirpur, Dhaka',
'Joar Sahara, Dhaka',
'Block B, Nobodoy Housing Society, Mohammadpur, Dhaka',
'Block D, Section 10, Mirpur, Dhaka',
'Farmgate, Tejgaon, Dhaka',
'Block E1, Chandrima Model Town, Mohammadpur, Dhaka',
'Wari, Sutrapur, Dhaka',
'South Bishil, Section 1, Mirpur, Dhaka',
'Pallabi, Mirpur, Dhaka',
'Chowdhuripara, Khilgaon, Dhaka',
'Naya Bazar, Bangshal, Dhaka',
'Azimpur, Lalbagh, Dhaka',
'Block I, Arifabad Housing Society, Pallabi, Mirpur, Dhaka', 
'Comfort Housing, Adabor, Dhaka',
'Rupnagar R/A, Mirpur, Dhaka',
'Block B, Bochila West Dhanmondi R/A, Bochila, Mohammadpur, Dhaka',
'Chalabon, Dakshin Khan, Dhaka',
'East Azampur, Dakshin Khan, Dhaka',
'Block A, Section 1, Mirpur, Dhaka',
'Bijoy Nagar, Purana Paltan, Motijheel, Dhaka',
'Shahid Nagar, Lalbagh, Dhaka',
'South Maniknagar, Maniknagar, Dhaka',
'Zafrabad, Dhaka',
'South Goran, Goran, Khilgaon, Dhaka',
'Dakkhin Paikpara, Mirpur, Dhaka',
'South Baridhara Residential Area,D. I. T. Project, Badda, Dhaka',
'Avenue 9, Mirpur DOHS, Mirpur, Dhaka',
'Block D, Arifabad Housing Society, Pallabi, Mirpur, Dhaka',
'Jurain, Shyampur, Dhaka',
'Luxmibazar, Sutrapur, Dhaka',
'Sadarghat, Kotwali, Dhaka',
'Arambag Residential Area, Mirpur, Dhaka',
'Gudaraghat, Middle Badda, Badda, Dhaka',
'Block C, Bashundhara R-A, Dhaka',
'Block N, South Banasree Project, Banasree, Dhaka',
'Sector 11, Uttara, Dhaka',
'North Ibrahimpur, Ibrahimpur, Dhaka',
'Kawlar, Dakshin Khan, Dhaka',
'South Mollartek, Dakshin Khan, Dhaka',
'Block B, South Banasree Project, Banasree, Dhaka',
'Block H, South Banasree Project, Banasree, Dhaka',
'West Kalachandpur, Kalachandpur, Dhaka',
'Block A, Chad Uddan Housing, Mohammadpur, Dhaka',
'Block D, Niketan, Dhaka',
'Mugdapara, Dhaka',
'Road No 9, Block A, Section 11, Mirpur, Dhaka',
'North Goran, Khilgaon, Dhaka',
'Sector 1, Block E, Aftab Nagar, Dhaka',
'Kalachandpur, Dhaka',
'Sector 9, Uttara, Dhaka',
'Dhanmondi, Dhaka', 
'Tolarbag, Section 1, Mirpur, Dhaka',
'West Katashur, Katashur, Mohammadpur, Dhaka',
'West Shewrapara, Mirpur, Dhaka',
'Sunibir Housing Society, Adabor, Dhaka',
'Taltola, Dakshin Khan, Dhaka',
'Lalmati, Block E, Section 11, Mirpur, Dhaka',
'Arambag Residential Area, Pallabi, Mirpur, Dhaka',
'Block C, South Banasree Project, Banasree, Dhaka',
'Road No 2, Block D, Bashundhara R-A, Dhaka',
'Matikata, Cantonment, Dhaka',
'Dhorangartek, Turag, Dhaka',
'Hazaribagh Road, Hazaribag, Dhaka',
'Block D2, Section 10, Mirpur, Dhaka',
'Bonobithi Abashik Alaka, East Azampur, Dakshin Khan, Dhaka',
'Block B, Future Town, Bochila, Mohammadpur, Dhaka',
'Panthapath, Kathalbagan, Dhaka',
'Ring Road, Mohammadpur, Dhaka',
'Block E, Lalmatia, Dhaka',
'Shaikh Saheb Bazar Road, Azimpur, Lalbagh, Dhaka',
'Block A, Aftab Nagar, Dhaka',
'Jahuri Moholla, Mohammadpur, Dhaka',
'Road No 12, Block B, Section 11, Mirpur, Dhaka',
'Bawaila Para, Badda, Dhaka',
'Block B, Section 6, Mirpur, Dhaka',
'Bochila Garden City, Bochila, Mohammadpur, Dhaka',
'Majed Sardar Road, Bangshal, Dhaka',
'Jigatola, Hazaribag, Dhaka',
'Block D, Section 11, Mirpur, Dhaka',
'Purana Paltan, Motijheel, Dhaka',
'South Goran, Khilgaon, Dhaka',
'Shahjahanpur, Dhaka',
'West Kafrul, Taltola, Dhaka',
'Shukrabad, Dhanmondi, Dhaka',
'Mohakhali DOHS, Dhaka',
'Block A, Section 11, Mirpur, Dhaka',
'Satarkul, Uttar Badda, Badda, Dhaka',
'Road No 5, Dhanmondi, Dhaka',
'RK Mission Road, Gopibag, Motijheel, Dhaka',
'Bonolota Abashik Elaka, West Agargaon, Agargaon, Dhaka',
'Block J, Baridhara, Dhaka',
'Gandaria, Sutrapur, Dhaka',
'Gojmohal, Hazaribag, Dhaka',
'Shantibag, Malibagh, Dhaka',
'Sector 2, Block F, Aftab Nagar, Dhaka',
'Block G/1, Section 2, Mirpur, Dhaka',
'1st Colony, Mirpur, Dhaka', 
'Bou Bazar, East Hazipara, East Rampura, Rampura, Dhaka',
'Block B, Chad Uddan Housing, Mohammadpur, Dhaka',
'Block F, Dhaka Uddan, Mohammadpur, Dhaka',
'TIC Colony, Faydabad, Dakshin Khan, Dhaka',
'Block A, Kaderabad Housing Society, Bosila, Mohammadpur, Dhaka',
'Kalibari, Rajarbag, Bashabo, Dhaka',
'North Shahjahanpur, Dhaka',
'Block D, South Banasree Project, Banasree, Dhaka',
'Nikunja 2, Nikunja, Dhaka',
'Bochila, Mohammadpur, Dhaka',
'Namapara, Khilkhet, Dhaka',
'Matikata Bazar Road, Matikata, Cantonment, Dhaka',
'Baridhara, Dhaka',
'Block A, Section 13, Mirpur, Dhaka',
'Sadarghat, Dhaka',
'Nobinbagh, West Meradia, Meradia, Khilgaon, Dhaka',
'Block B, Pallabi, Mirpur, Dhaka',
'Taltola, Agargaon, Dhaka',
'Atish Deepankar Road, Bashabo, Dhaka',
'Goltek, Cantonment, Dhaka',
'Road No 10, Block C, Section 11, Mirpur, Dhaka',
'Sector 1, Uttara, Dhaka',
'Block A, Future Town, Bochila, Mohammadpur, Dhaka',
'Block J, Section 3, Mirpur, Dhaka',
'East Rasulpur, Rasulpur, Donia, Jatra Bari, Dhaka',
'Block D, Section 2, Mirpur, Dhaka',
'Ray Shaheb Bazar, Sutrapur, Dhaka',
'Chowdhury Bazar, Lalbagh, Dhaka',
'Block A, Dhaka Uddan, Mohammadpur, Dhaka',
'Nobodoy Housing Society, Mohammadpur, Dhaka',
'Block C, Section 10, Mirpur, Dhaka',
'Block J, Eastern Housing, Pallabi, Mirpur, Dhaka',
'Kajla, Jatra Bari, Dhaka',
'Mofizbag Housing, Shekhertek, Mohammadpur, Dhaka',
'Banglamotors, Dhaka',
'Block D, Metro Housing, Bochila, Mohammadpur, Dhaka',
'Bot Tola, Khilkhet, Dhaka',
'Avenue 6, Mirpur DOHS, Mirpur, Dhaka',
'Chairman Para, Dakshin Khan, Dhaka',
'Shamibag, Sutrapur, Dhaka',
'Block A, Eastern Housing, Pallabi, Mirpur, Dhaka',
'Block E, Section 2, Mirpur, Dhaka',
'Block B, Niketan, Dhaka',
'Block L, Bashundhara R-A, Dhaka',
'Shadhinata Sharani, Uttar Badda, Badda, Dhaka',
'Block A, Rajuk Uttara Apartment Project, Sector 18, Uttara, Dhaka',
'Block A, Section 2, Mirpur, Dhaka',
'Dhaka Uddan, Mohammadpur, Dhaka',
'Lalbagh, Dhaka',
'Block B, Eastern Housing, Pallabi, Mirpur, Dhaka',
'Madartek, East Bashabo, Bashabo, Dhaka',
'Block B, Dakkhin Paikpara, Paikpara, Mirpur, Dhaka',
'Avenue 2, Block A, Section 13, Mirpur, Dhaka',
'Sher-E-Bangla Avenue, Dolipara, Uttara, Dhaka',
'Baridhara DOHS, Dhaka',
'Naya Paltan, Motijheel, Dhaka',
'Block D, Lalmatia, Dhaka',
'Shahidbag, Malibagh, Dhaka',
'Bagan Bari, Cantonment, Dhaka',
'Moushan East Para, Kuril, Dhaka',
'Block C, Chandmiya Housing, Mohammadpur, Dhaka',
'Janata Housing, Shah Ali Bag, Section 1, Mirpur, Dhaka',
'Middle Monipur, Mirpur, Dhaka',
'West Dolairpar, Shyampur, Dhaka', 
'West Jatrabari, Jatra Bari, Dhaka',
'Block F, aziz Moholla, Mohammadpur, Dhaka',
'Middle Paikpara, Mirpur, Dhaka',
'Arifabad Housing Society, Pallabi, Mirpur, Dhaka',
'Kahektuli, Bangshal, Dhaka',
'Avenue 2, Mirpur DOHS, Mirpur, Dhaka',
'Section 13, Mirpur, Dhaka',
'Faydabad, Dakshin Khan, Dhaka',
'Block Cha, Section 2, Mirpur, Dhaka',
'Nayatola, Boro Maghbazar, Maghbazar, Dhaka',
'Saat Rawza, Bangshal, Dhaka',
'Block K, Baridhara, Dhaka',
'North Adabor, Adabor, Dhaka',
'Mohammadi Homes R/A, Mohammadpur, Dhaka',
'Ward 6, West Nurer Chala, Nurer Chala, Badda, Dhaka',
'West Nurer Chala, Nurer Chala, Badda, Dhaka',
'Lake View Society, South Pirerbag, Pirerbag, Mirpur, Dhaka',
'Block J, Banasree, Dhaka',
'Block A, Niketan, Dhaka',
'Adarsha Nagar, Badda, Dhaka',
'Sayem Sobhan Anvir Road, Block C, Bashundhara R-A, Dhaka',
'Aftab Nagar, Dhaka',
'22 Bari, West Kazipara, Mirpur, Dhaka',
'Turag City, Section 1, Mirpur, Dhaka',
'Block F, Arambag Residential Area, Pallabi, Mirpur, Dhaka',
'Malibag Bazar Rd, Malibagh, Dhaka',
'South Mugdapara, Mugdapara, Dhaka',
'Kadamtala Road, Kadamtala, Bashabo, Dhaka',
'Mannan Sharani, West Shewrapara, Mirpur, Dhaka',
'Kaderabad Housing Society, Bosila, Mohammadpur, Dhaka',
'Niketan, Dhaka',
'Block A, Kaderabad Housing Society, Katashur, Mohammadpur, Dhaka',
'Adarsha Para, Uttar Khan, Dhaka',
'Tilpapara Road, Tilpapara, Khilgaon, Dhaka',
'Dhaka Real Estate, Katashur, Mohammadpur, Dhaka',
'Madartek, Bashabo, Dhaka',
'Block I Extension, Bashundhara R-A, Dhaka',
'Amligola, Lalbagh, Dhaka',
'Hatimbag, Dakshin Khan, Dhaka',
'Block D, Dhaka Uddan, Mohammadpur, Dhaka',
'Middle Bashabo, Bashabo, Dhaka',
'Block B, Section 10, Mirpur, Dhaka',
'Green Road, Dhanmondi, Dhaka',
'Anurbag, Dakshin Khan, Dhaka',
'Vatara, Badda, Dhaka',
'Block B, Bashundhara R-A, Dhaka',
'Future Town, Bochila, Mohammadpur, Dhaka',
'Ahmed Nagar, Mirpur, Dhaka',
'Hazaribag Model Town, Hazaribag, Dhaka',
'Block E, Kaderabad Housing Society, Bosila, Mohammadpur, Dhaka',
'Block A, Mohanagar Housing, West Rampura, Rampura, Dhaka',
'Pirerbag, Section 1, Mirpur, Dhaka',
'Sector 6, Uttara, Dhaka',
'East Hazipara, East Rampura, Rampura, Dhaka',
'Block B, Section 11, Mirpur, Dhaka',
'Tallabag, Hazaribag, Dhaka', 
'Avenue 3, Mirpur DOHS, Mirpur, Dhaka',
'Block F, Aftab Nagar, Dhaka',
'Block B, Section 1, Mirpur, Dhaka',
'Section 2, Mirpur, Dhaka',
'Shamibag Road, Shamibag, Sutrapur, Dhaka',
'Tekpara, Badda, Dhaka',
'Khilgaon, Dhaka',
'Naya Nagar, Vatara, Badda, Dhaka',
'Mohakhali, Dhaka',
'Block F, Section 11, Mirpur, Dhaka',
'South Azampur, Dakshin Khan, Dhaka',
'North Goran, Goran, Khilgaon, Dhaka',
'Block C Extension, Banasree, Dhaka',
'Block E, Niketan, Dhaka',
'North Mugdapara, Mugdapara, Dhaka',
'Katabon, New Market, Dhaka',
'Sobhanbagh, Tejgaon, Dhaka',
'aziz Moholla, Mohammadpur, Dhaka',
'Mohammadi Housing LTD., Mohammadpur, Dhaka',
'Sector 3, Uttara, Dhaka',
'East Manikdi, Manikdi, Cantonment, Dhaka',
'Avenue 7, Mirpur DOHS, Mirpur, Dhaka',
'Block D, Chandrima Model Town, Mohammadpur, Dhaka',
'Ranavola- Block D, Sector 10, Uttara, Dhaka',
'East Madartek, Madartek, Bashabo, Dhaka',
'Section 12, Mirpur, Dhaka',
'Block G, Section 2, Mirpur, Dhaka',
'Suchona Model Town, Bochila, Mohammadpur, Dhaka',
'Shardar Bari, Dakshin Khan, Dhaka',
'Shuritola, Bangshal, Dhaka',
'Block G, South Banasree Project, Banasree, Dhaka',
'Bibir Bagicha, Jatra Bari, Dhaka',
'Faidabad Garden City, Faydabad, Dakshin Khan, Dhaka',
'Banasree, Dhaka',
'Block D, Mohanagar Housing, West Rampura, Rampura, Dhaka',
'North Jatra Bari, Jatra Bari, Dhaka',
'North Shahjahanpur, Shahjahanpur, Dhaka',
'Kuratoli, Kuril, Dhaka',
'Boshoty Housing, Borobag, Section 2, Mirpur, Dhaka',
'Malibagh, Dhaka',
'Block G, Section 1, Mirpur, Dhaka',
'Latif Real Estate, Katashur, Mohammadpur, Dhaka',
'Rajabazar, Tejgaon, Dhaka',
'Block F, Banasree, Dhaka',
'Block D, Section 6, Mirpur, Dhaka',
'Block A, Banasree, Dhaka',
'Block A, Pallabi, Mirpur, Dhaka',
'South Jatra Bari, Jatra Bari, Dhaka',
'Block C, Bochila Garden City, Bochila, Mohammadpur, Dhaka',
'Uttar Para, Khilkhet, Dhaka',
'Mazar Road, 2nd Colony, Mirpur, Dhaka',
'Jhauchor, Hazaribag, Dhaka',
'Block M, Banasree, Dhaka',
'Jagannath Shaha Road, Amligola, Lalbagh, Dhaka',
'Shantipur, South Goran, Goran, Khilgaon, Dhaka',
'Road No 12, Sector 4, Uttara, Dhaka',
'Kathalbagan, Dhaka',
'Tejgaon, Dhaka',
'Uttara, Dhaka',
'West Dhanmondi and Shangkar, Dhanmondi, Dhaka',
'Sector 1, Block D, Aftab Nagar, Dhaka',
'Narinda, Sutrapur, Dhaka',
'Solmaid, Badda, Dhaka',
'Shah Ali Bag, Section 1, Mirpur, Dhaka',
'West Kafrul, Taltola, Agargaon, Dhaka', 
'Block D, Kaderabad Housing Society, Bosila, Mohammadpur, Dhaka',
'Sipahibagh, North Goran, Goran, Khilgaon, Dhaka',
'Block C1, Sector 15, Uttara, Dhaka',
'Block A, Chandrima Model Town, Mohammadpur, Dhaka',
'Nikunja 1, Nikunja, Dhaka',
'Taltola, Khilgaon, Dhaka',
'Block B, Kaderabad Housing Society, Bosila, Mohammadpur, Dhaka',
'Block B, Dolipara, Uttara, Dhaka',
'West Vatara, Vatara, Badda, Dhaka',
'Mahuthtuli, Bangshal, Dhaka',
'Block F, Bashundhara R-A, Dhaka',
'Block C, Nobodoy Housing Society, Mohammadpur, Dhaka',
'East Bashabo, Bashabo, Dhaka',
'Uttar Khan, Dhaka',
'Middle Pirerbag, Pirerbag, Mirpur, Dhaka',
'Road No 17, Sector 12, Uttara, Dhaka',
'Block A, Bashundhara R-A, Dhaka',
'Block C, Kaderabad Housing Society, Bosila, Mohammadpur, Dhaka',
'Road No 4, Block G, Bashundhara R-A, Dhaka',
'Shegunbagicha, Dhaka',
'Boatghat, Namapara, Khilkhet, Dhaka',
'Uttar Badda, Badda, Dhaka',
'Sector 2, Block D, Aftab Nagar, Dhaka',
'Block C, Future Town, Bochila, Mohammadpur, Dhaka',
'New Market, Dhaka',
'Rokonpur, Kolta Bazar, Sutrapur, Dhaka',
'Block B, Arambag Residential Area, Pallabi, Mirpur, Dhaka',
'Block A, Bochila Garden City, Bochila, Mohammadpur, Dhaka',
'Avenue 5, Block C, Section 11, Mirpur, Dhaka',
'Block G, Eastern Housing, Pallabi, Mirpur, Dhaka',
'Aainusbag, Dakshin Khan, Dhaka',
'Mir Hajir Bag Road, West Dolairpar, Shyampur, Dhaka',
'Block H, Aftab Nagar, Dhaka',
'West Rampura, Rampura, Dhaka',
'Block F, South Banasree Project, Banasree, Dhaka',
'Abur Tek, Khilkhet, Dhaka',
'Monipur, Mirpur, Dhaka',
'Block D, Kaderabad Housing Society, Katashur, Mohammadpur, Dhaka',
'Cantonment, Dhaka',
'Boro Maghbazar, Maghbazar, Dhaka',
'Block D, Dolipara, Uttara, Dhaka',
'Golartek, Section 1, Mirpur, Dhaka',
'North Azampur, Dakshin Khan, Dhaka',
'Shyamoli Housing (2nd Project), Adabor, Dhaka',
'Section 7, Mirpur, Dhaka',
'Avenue 5, Mirpur DOHS, Mirpur, Dhaka',
'Turag, Dhaka',
'Natun Bazar, Badda, Dhaka',
'South Madartek, Madartek, Bashabo, Dhaka',
'Popular Housing, Borobag, Section 2, Mirpur, Dhaka',
'Baithakali, Badda, Dhaka',
'Block E, Section 12, Mirpur, Dhaka',
'Naddapara, Dakshin Khan, Dhaka',
'Faydabad, East Azampur, Dakshin Khan, Dhaka',
'Sujat Nagar, Pallabi, Mirpur, Dhaka',
'Abdullahbag, Uttar Badda, Badda, Dhaka',
'Bhuiya Estate, Jhauchor, Hazaribag, Dhaka',
'Kuril, Dhaka',
'Sector 15, Uttara, Dhaka',
'Ward 9, East Khilbari Tek, Khilbari Tek, Badda, Dhaka',
'Kachukhet, Dhaka',
'Old Eskaton, Eskaton, Dhaka',
'Block E, Eastern Housing, Pallabi, Mirpur, Dhaka',
'North Pirerbag, Pirerbag, Section 1, Mirpur, Dhaka',
'Block B, Bochila City Developers Ltd, Bochila, Mohammadpur, Dhaka',
'Konapara, Demra, Dhaka',
'Block C, Chandrima Model Town, Mohammadpur, Dhaka',
'Block L, Eastern Housing, Pallabi, Mirpur, Dhaka',
'Ward 98, Rampura, Dhaka',
'Mohammadia Housing Society, Mohammadpur, Dhaka', 
'Naya Nagar, Khilkhet, Dhaka',
'Block A, Section 12, Mirpur, Dhaka',
'Ali And Nur Real Estate, Mohammadpur, Dhaka',
'Shiddheswari, Dhaka',
'Middle Badda, Badda, Dhaka',
'Badda, Dhaka',
'Banani DOHS, Dhaka',
'Road No 11, Block C, Section 11, Mirpur, Dhaka',
'Sector 1, Block K, Aftab Nagar, Dhaka',
'Sayedabad, Jatra Bari, Dhaka',
'Avenue 3, Block B, Section 11, Mirpur, Dhaka',
'West Maniknagar, Maniknagar, Dhaka',
'Sutrapur, Dhaka',
'Block E, Chandrima Model Town, Mohammadpur, Dhaka',
'West Kazipara, Mirpur, Dhaka',
'Maniknagar, Dhaka',
'Avenue 10, Mirpur DOHS, Mirpur, Dhaka',
'Avenue 4, Mirpur DOHS, Mirpur, Dhaka',
'Katashur, Mohammadpur, Dhaka',
'Vhatara Road, Natun Bazar, Badda, Dhaka',
'Block A, Arambag Residential Area, Pallabi, Mirpur, Dhaka',
'Moddo Para, Khilkhet, Dhaka',
'Block K, Eastern Housing, Pallabi, Mirpur, Dhaka',
'North Bishil, Section 1, Mirpur, Dhaka',
'Gawair, Dakshin Khan, Dhaka',
'South Matuail, Matuail, Demra, Dhaka',
'Block A, Rainkhola, Section 2, Mirpur, Dhaka',
'Jatra Bari, Dhaka',
'Kaderabad Housing Society, Katashur, Mohammadpur, Dhaka',
'Malibagh Chowdhury Para, Malibagh, Dhaka',
'Priyanka City, Sector 12, Uttara, Dhaka',
'Block Ka, North Bishil, Section 1, Mirpur, Dhaka',
'Talertek, Khilkhet, Dhaka',
'Manikdi, Cantonment, Dhaka',
'Sher- E- Banglanagar, West Agargaon, Agargaon, Dhaka',
'Block D, Mansurabad Housing Society, Adabor, Dhaka',
'Road No 5, Sector 10, Uttara, Dhaka',
'Gulbag, Malibagh, Dhaka',
'Block G, Bashundhara R-A, Dhaka',
'3rd Colony, Mirpur, Dhaka',
'Kazibari, Dakshin Khan, Dhaka',
'Block F, Mohammadpur, Dhaka',
'Block C, Arambag Residential Area, Pallabi, Mirpur, Dhaka',
'East Nakhalpara, Tejgaon, Dhaka',
'Block Ka, Section 6, Mirpur, Dhaka',
'Nurer Chala, Badda, Dhaka',
'Block New C, Section 1, Mirpur, Dhaka',
'Block A, Sat Masjid Housing, Mohammadpur, Dhaka',
'North Kalachandpur, Kalachandpur, Dhaka',
'Lalkuthi, 3rd Colony, Mirpur, Dhaka',
'Purbanchal Road, Uttar Badda, Badda, Dhaka',
'Block E, South Banasree Project, Banasree, Dhaka',
'Chandmiya Housing, Mohammadpur, Dhaka',
'Block D, Section 12, Mirpur, Dhaka',
'Block D, Section 15, Mirpur, Dhaka',
'Kellar Mor, Lalbagh, Dhaka',
'South Badda, Badda, Dhaka',
'Jhilpar, Middle Pirerbag, Pirerbag, Mirpur, Dhaka',
'Block B, Mohanagar Housing, West Rampura, Rampura, Dhaka',
'Shyamoli, Dhaka',
'Sector 7, Uttara, Dhaka',
'Section 11, Mirpur, Dhaka',
'Mohanagar Housing, West Rampura, Rampura, Dhaka',
'Road No 7, Block E, Banasree, Dhaka',
'Shantinagar, Dhaka',
'Elephant Road, New Market, Dhaka',
'Avenue 2A, Mirpur DOHS, Mirpur, Dhaka',
'Sector 13, Uttara, Dhaka',
'Block M, South Banasree Project, Banasree, Dhaka',
'Sector 4, Uttara, Dhaka',
'Block TA, Section 6, Mirpur, Dhaka',
'Old Elephant Road, Maghbazar, Dhaka',
'Duip R-A, Block A, Section 2, Mirpur, Dhaka',
'East Kazipara, Mirpur, Dhaka',
'Maghbazar, Dhaka',
'Pirerbag, Mirpur, Dhaka',
'Block C, Banasree, Dhaka',
'Jamtola, Kawlar, Dakshin Khan, Dhaka',
'Hatirpool, Dhaka',
'Block E, Section 6, Mirpur, Dhaka',
'Motijheel, Dhaka',
'Nayatola, Maghbazar, Dhaka', 
'Mollartek, Dakshin Khan, Dhaka',
'Block C, Eastern Housing, Pallabi, Mirpur, Dhaka',
'Road No 18/A, Block E, Bashundhara R-A, Dhaka',
'Kamlapur, Motijheel, Dhaka',
'Block E, Arifabad Housing Society, Pallabi, Mirpur, Dhaka',
'New Eskaton, Eskaton, Dhaka',
'Hazipara, Dakshin Khan, Dhaka',
'Monipuripara, Tejgaon, Dhaka',
'Mirpur, Dhaka',
'Block I, Bashundhara R-A, Dhaka',
'East Shewrapara, Mirpur, Dhaka',
'North Kamlapur, Kamlapur, Motijheel, Dhaka',
'Block H, Section 2, Mirpur, Dhaka',
'Moddhopara, Ashkona, Dakshin Khan, Dhaka',
'Block B, Notunbag, Taltola, Khilgaon, Dhaka',
'Section 10, Mirpur, Dhaka',
'Baigertek, Cantonment, Dhaka',
'Block D, Banasree, Dhaka',
'Block A, Nobodoy Housing Society, Mohammadpur, Dhaka',
'Road No 8, Block A, Section 11, Mirpur, Dhaka',
'Keraniganj, Dhaka',
'Pallabi Extension, Pallabi, Mirpur, Dhaka',
'Agargaon, Dhaka',
'Kamarpara, Turag, Dhaka',
'South Manikdi, Manikdi, Cantonment, Dhaka',
'Block C, Dakkhin Paikpara, Paikpara, Mirpur, Dhaka',
'Block H, Banasree, Dhaka',
'Baitul Aman Housing Society, Adabor, Dhaka',
'Block A, Lalmatia, Dhaka',
'Begum Bazar, Bangshal, Dhaka',
'Sector 5, Uttara, Dhaka',
'Paribagh, Dhaka',
'Vashantek, Cantonment, Dhaka',
'Avenue 2, Block A, Section 11, Mirpur, Dhaka',
'Section 3, Mirpur, Dhaka',
'South Chalabon, Dakshin Khan, Dhaka',
'Moneshwar, Hazaribag, Dhaka',
'Goaltek, Faydabad, Dakshin Khan, Dhaka',
'Kafrul, Dhaka',
'North Manikdi, Manikdi, Cantonment, Dhaka',
'North Vashantek, Vashantek, Cantonment, Dhaka',
'Block J, Bashundhara R-A, Dhaka',
'South Doniya, Doniya, Shyampur, Dhaka',
'Tejkunipara, Tejgaon, Dhaka',
'Arambagh, Motijheel, Dhaka',
'Block K, Bashundhara R-A, Dhaka',
'Section 15, Mirpur, Dhaka',
'Block A, Section 6, Mirpur, Dhaka',
'Janata Housing, Sher- E- Banglanagar, West Agargaon, Agargaon, Dhaka',
'West Monipur, Mirpur, Dhaka',
'Block B, Metro Housing, Bochila, Mohammadpur, Dhaka',
'Matuail, Demra, Dhaka',
'East Rampura, Rampura, Dhaka',
'Bhagalpur, Hazaribag, Dhaka',
'Block K, Aftab Nagar, Dhaka',
'Block K, South Banasree Project, Banasree, Dhaka',
'Section 1, Mirpur, Dhaka',]
