from math import floor
from django.shortcuts import render, HttpResponseRedirect, reverse
from django.http import HttpResponse
import pickle

location_dictionary = {'Block H, Bashundhara R-A, Dhaka': 238,
 'Farmgate, Tejgaon, Dhaka': 328,
 'Block B, Nobodoy Housing Society, Mohammadpur, Dhaka': 125,
 'Gulshan 1, Gulshan, Dhaka': 345,
 'Baridhara, Dhaka': 59,
 'Bashundhara R-A, Dhaka': 62,
 'PC Culture Housing, Mohammadpur, Dhaka': 519,
 'Jigatola, Hazaribag, Dhaka': 370,
 'West Kazipara, Mirpur, Dhaka': 713,
 'Block D, Bashundhara R-A, Dhaka': 173,
 'Block J, Bashundhara R-A, Dhaka': 247,
 'Nikunja 2, Nikunja, Dhaka': 491,
 'Sector 6, Uttara, Dhaka': 603,
 'Khilgaon, Dhaka': 402,
 'Block K, Baridhara, Dhaka': 253,
 'Ibrahimpur, Dhaka': 355,
 'Sector 5, Uttara, Dhaka': 602,
 'Nurer Chala, Badda, Dhaka': 515,
 'Block F, Bashundhara R-A, Dhaka': 220,
 'Sector 4, Uttara, Dhaka': 601,
 'Rajabazar, Tejgaon, Dhaka': 538,
 'Sector 9, Uttara, Dhaka': 605,
 'Sector 14, Uttara, Dhaka': 594,
 'Block D, Section 12, Mirpur, Dhaka': 194,
 'Block G, Bashundhara R-A, Dhaka': 230,
 'Baitul Aman Housing Society, Adabor, Dhaka': 51,
 'Kajla, Jatra Bari, Dhaka': 380,
 'Sector 11, Uttara, Dhaka': 591,
 'Sector 7, Uttara, Dhaka': 604,
 'Gulshan 2, Gulshan, Dhaka': 346,
 'Sector 10, Uttara, Dhaka': 590,
 'Block A, Sat Masjid Housing, Mohammadpur, Dhaka': 94,
 'West Malibag, Malibagh, Dhaka': 714,
 'Banani, Dhaka': 54,
 'Block A, Bashundhara R-A, Dhaka': 73,
 'Kakrail, Dhaka': 381,
 'Block I, Bashundhara R-A, Dhaka': 244,
 'Malibagh, Dhaka': 427,
 'West Dhanmondi and Shangkar, Dhanmondi, Dhaka': 705,
 'Maghbazar, Dhaka': 422,
 'Block I Extension, Bashundhara R-A, Dhaka': 242,
 'West Kalachandpur, Kalachandpur, Dhaka': 711,
 'Sector 3, Uttara, Dhaka': 600,
 'Badda, Dhaka': 47,
 'Mohammadpur, Dhaka': 461,
 'Block K, Bashundhara R-A, Dhaka': 254,
 'East Badda, Badda, Dhaka': 305,
 'Dhanmondi, Dhaka': 296,
 'Kamal Sarani, South Pirerbag, Pirerbag, Mirpur, Dhaka': 386,
 'Block A, Niketan, Dhaka': 89,
 'East Goran, Goran, Khilgaon, Dhaka': 307,
 'Block C, Section 13, Mirpur, Dhaka': 162,
 'Block B, Bashundhara R-A, Dhaka': 107,
 'New Eskaton, Eskaton, Dhaka': 487,
 'Mirpur, Dhaka': 451,
 'Block C, Bashundhara R-A, Dhaka': 141,
 'Block H, Banasree, Dhaka': 237,
 'Middle Monipur, Mirpur, Dhaka': 444,
 'Block B, Niketan, Dhaka': 124,
 'Monipuripara, Tejgaon, Dhaka': 467,
 'Niketan, Dhaka': 489,
 'Shantibag, Malibagh, Dhaka': 618,
 'Block F, aziz Moholla, Mohammadpur, Dhaka': 228,
 'East Bashabo, Bashabo, Dhaka': 306,
 'Block A, Kaderabad Housing Society, Bosila, Mohammadpur, Dhaka': 83,
 'Baridhara DOHS, Dhaka': 58,
 'Sector 13, Uttara, Dhaka': 593,
 'Mohammadi Housing LTD., Mohammadpur, Dhaka': 459,
 'Tejgaon, Dhaka': 677,
 'Sector 12, Uttara, Dhaka': 592,
 'Dhaka Real Estate, Katashur, Mohammadpur, Dhaka': 294,
 'Block A, Chandrima Model Town, Mohammadpur, Dhaka': 79,
 'Block A, Section 11, Mirpur, Dhaka': 98,
 'Middle Pirerbag, Pirerbag, Mirpur, Dhaka': 446,
 'Block A, Banasree, Dhaka': 72,
 'Block C, Aftab Nagar, Dhaka': 138,
 'Block D, Section 2, Mirpur, Dhaka': 196,
 'West Shewrapara, Mirpur, Dhaka': 724,
 'Nayatola, Maghbazar, Dhaka': 485,
 'Block C, Section 2, Mirpur, Dhaka': 163,
 'Middle Paikpara, Mirpur, Dhaka': 445,
 'Taltola, Khilgaon, Dhaka': 675,
 'South Monipur, Mirpur, Dhaka': 656,
 'Dolipara, Uttara, Dhaka': 299,
 'Pirerbag, Mirpur, Dhaka': 528,
 'Eskaton, Dhaka': 325,
 'Lalmatia, Dhaka': 415,
 '1st Colony, Mirpur, Dhaka': 0,
 'Uttar Badda, Badda, Dhaka': 691,
 'Chandmiya Housing, Mohammadpur, Dhaka': 283,
 'East Merul Badda, Merul Badda, Badda, Dhaka': 314,
 'Avenue 3, Mirpur DOHS, Mirpur, Dhaka': 38,
 'Faydabad, Dakshin Khan, Dhaka': 329,
 'Sector 1, Block F, Aftab Nagar, Dhaka': 586,
 'Sector 2, Block F, Aftab Nagar, Dhaka': 598,
 'Section 2, Mirpur, Dhaka': 581,
 'Block C, Kaderabad Housing Society, Bosila, Mohammadpur, Dhaka': 151,
 'Mohammadia Housing Society, Mohammadpur, Dhaka': 460,
 'Block D, Mansurabad Housing Society, Adabor, Dhaka': 185,
 'Mohakhali DOHS, Dhaka': 456,
 'Sector 1, Uttara, Dhaka': 589,
 'Block J, Baridhara, Dhaka': 246,
 'Kallyanpur, Mirpur, Dhaka': 385,
 'Shyamoli Housing, Shekhertek, Mohammadpur, Dhaka': 631,
 'Wari, Sutrapur, Dhaka': 703,
 'Hatirpool, Dhaka': 349,
 'South Pirerbag, Pirerbag, Mirpur, Dhaka': 658,
 'Taltola, Agargaon, Dhaka': 672,
 'Gawair, Dakshin Khan, Dhaka': 333,
 'Mollika R/A, Section 7, Mirpur, Dhaka': 464,
 'Road No 4, Block G, Bashundhara R-A, Dhaka': 557,
 'Gulbag, Malibagh, Dhaka': 344,
 'Jamtola, East Rampura, Rampura, Dhaka': 360,
 'Tejkunipara, Tejgaon, Dhaka': 678,
 'Block C, Nobodoy Housing Society, Mohammadpur, Dhaka': 157,
 'Road No 5, Sector 10, Uttara, Dhaka': 559,
 'Pallabi Extension, Pallabi, Mirpur, Dhaka': 523,
 'Modhubag, Boro Maghbazar, Maghbazar, Dhaka': 454,
 'Block L, Bashundhara R-A, Dhaka': 260,
 'Avenue 1, Mirpur DOHS, Mirpur, Dhaka': 26,
 'Cantonment, Dhaka': 280,
 'Shahbagh, Dhaka': 610,
 'Banasree, Dhaka': 55,
 'Block E, Banasree, Dhaka': 203,
 'Khilkhet, Dhaka': 403,
 'Block A, Nobodoy Housing Society, Mohammadpur, Dhaka': 90,
 'Uttara, Dhaka': 695,
 'Block A, Chad Uddan Housing, Mohammadpur, Dhaka': 77,
 'Block B, Aftab Nagar, Dhaka': 104,
 'Section 12, Mirpur, Dhaka': 578,
 'Section 10, Mirpur, Dhaka': 576,
 'Dakkhin Paikpara, Paikpara, Mirpur, Dhaka': 291,
 'Naya Paltan, Motijheel, Dhaka': 483,
 'Tikatuli, Sutrapur, Dhaka': 681,
 'Shantinagar, Dhaka': 619,
 'Shegunbagicha, Dhaka': 622,
 'Motijheel, Dhaka': 468,
 'Block A, Rajuk Uttara Apartment Project, Sector 18, Uttara, Dhaka': 93,
 'Block B, Banasree, Dhaka': 106,
 'Goran, Khilgaon, Dhaka': 340,
 'East Shewrapara, Mirpur, Dhaka': 321,
 'Block D, Mohanagar Housing, West Rampura, Rampura, Dhaka': 187,
 'Block F, Section 11, Mirpur, Dhaka': 225,
 'Kathalbagan, Dhaka': 393,
 'Merul Badda, Badda, Dhaka': 439,
 'Tilpapara, Khilgaon, Dhaka': 683,
 'Block A, Lalmatia, Dhaka': 85,
 'Kalachandpur, Dhaka': 383,
 'Senpara Parbata, Section 10, Mirpur, Dhaka': 606,
 'East Rampura, Rampura, Dhaka': 319,
 'South Banasree Project, Banasree, Dhaka': 640,
 'Section 1, Mirpur, Dhaka': 575,
 'North Pirerbag, Pirerbag, Mirpur, Dhaka': 509,
 'RK Mission Road, Gopibag, Motijheel, Dhaka': 537,
 'Block A, Mohanagar Housing, West Rampura, Rampura, Dhaka': 88,
 'Avenue 6, Mirpur DOHS, Mirpur, Dhaka': 42,
 'Shyamoli, Dhaka': 632,
 'Kalabagan, Dhaka': 382,
 'Road No 7, Block E, Banasree, Dhaka': 560,
 'Hazaribag, Dhaka': 351,
 'Avenue 2, Mirpur DOHS, Mirpur, Dhaka': 33,
 'Priyanka City, Sector 12, Uttara, Dhaka': 533,
 'Dogair, Demra, Dhaka': 298,
 'Kuril, Dhaka': 408,
 'Gandaria, Sutrapur, Dhaka': 332,
 'Pallabi, Mirpur, Dhaka': 524,
 'Road No 16, Banani, Dhaka': 553,
 'Avenue 4, Mirpur DOHS, Mirpur, Dhaka': 39,
 'Boro Maghbazar, Maghbazar, Dhaka': 274,
 'Rampura, Dhaka': 541,
 'Agargaon, Dhaka': 13,
 'Block F, Banasree, Dhaka': 219,
 'Block A, Section 2, Mirpur, Dhaka': 101,
 'Dakshin Khan, Dhaka': 292,
 'Comfort Housing, Adabor, Dhaka': 289,
 'Satarkul, Uttar Badda, Badda, Dhaka': 571,
 'Namapara, Khilkhet, Dhaka': 476,
 'Avenue 5, Block C, Section 11, Mirpur, Dhaka': 40,
 'Mohakhali, Dhaka': 457,
 'Block M, South Banasree Project, Banasree, Dhaka': 264,
 'Block E, Section 2, Mirpur, Dhaka': 213,
 'Block B, Section 12, Mirpur, Dhaka': 132,
 'Shahid Nagar, Lalbagh, Dhaka': 611,
 'Block J, Banasree, Dhaka': 245,
 'South Baridhara Residential Area,D. I. T. Project, Badda, Dhaka': 641,
 'Mirpur DOHS, Mirpur, Dhaka': 449,
 'Block D, Lalmatia, Dhaka': 184,
 'New Market, Dhaka': 488,
 'Avenue 9, Mirpur DOHS, Mirpur, Dhaka': 45,
 'Madhya Ajampur, Dakshin Khan, Dhaka': 421,
 'Kafrul, Dhaka': 378,
 'Tolarbag, Section 1, Mirpur, Dhaka': 684,
 'Ullan, West Rampura, Rampura, Dhaka': 690,
 'South Chalabon, Dakshin Khan, Dhaka': 644,
 'Kachukhet, Dhaka': 373,
 'Azimpur, Lalbagh, Dhaka': 46,
 'Block E, Bashundhara R-A, Dhaka': 204,
 'Shukrabad, Dhanmondi, Dhaka': 628,
 'Block C, Bochila City Developers Ltd, Bochila, Mohammadpur, Dhaka': 142,
 'Kaderabad Housing Society, Katashur, Mohammadpur, Dhaka': 377,
 'Amligola, Lalbagh, Dhaka': 17,
 'Meradia, Khilgaon, Dhaka': 438,
 'Block B, Mansurabad Housing Society, Adabor, Dhaka': 120,
 'Kamarpara, Turag, Dhaka': 388,
 'North Gawair, Gawair, Dakshin Khan, Dhaka': 499,
 'Block A, Aftab Nagar, Dhaka': 69,
 'Block G, Section 1, Mirpur, Dhaka': 232,
 'Mollartek, Dakshin Khan, Dhaka': 463,
 'Shahjadpur, Badda, Dhaka': 613,
 'Block C, Section 12, Mirpur, Dhaka': 161,
 'Block D, Section 11, Mirpur, Dhaka': 193,
 'Block D, South Banasree Project, Banasree, Dhaka': 198,
 'Block B, South Banasree Project, Banasree, Dhaka': 136,
 '2nd Lane, Gopibag, Motijheel, Dhaka': 3,
 'Manikdi, Cantonment, Dhaka': 428,
 'Block A, Section 10, Mirpur, Dhaka': 97,
 'West Monipur, Mirpur, Dhaka': 718,
 'Rokonpur, Kolta Bazar, Sutrapur, Dhaka': 563,
 'Middle Badda, Badda, Dhaka': 440,
 'East Kazipara, Mirpur, Dhaka': 309,
 'Section 7, Mirpur, Dhaka': 583,
 'South Goran, Goran, Khilgaon, Dhaka': 646,
 'Tajmahal Road, Mohammadpur, Dhaka': 668,
 'Block F, Section 2, Mirpur, Dhaka': 226,
 'Block B, Section 11, Mirpur, Dhaka': 131,
 'Kadamtala, Bashabo, Dhaka': 375,
 'Block D, Section 10, Mirpur, Dhaka': 192,
 'West Rampura, Rampura, Dhaka': 723,
 'Block E, Section 12, Mirpur, Dhaka': 212,
 'Paikpara, Ahmed Nagar, Mirpur, Dhaka': 520,
 'Nadda, Dhaka': 474,
 'Chowdhuripara, Khilgaon, Dhaka': 287,
 'South Doniya, Doniya, Shyampur, Dhaka': 645,
 'East Maniknagar, Maniknagar, Dhaka': 313,
 'Block D, Eastern Housing, Pallabi, Mirpur, Dhaka': 180,
 'Sector 2, Block H, Aftab Nagar, Dhaka': 599,
 'Ullan, Rampura, Dhaka': 689,
 'Baigertek, Cantonment, Dhaka': 49,
 'Block E, Lalmatia, Dhaka': 208,
 'Road No 10, Block C, Section 11, Mirpur, Dhaka': 549,
 'Block Dha, Section 12, Mirpur, Dhaka': 200,
 'Banani DOHS, Dhaka': 53,
 'Boatghat, Namapara, Khilkhet, Dhaka': 269,
 'Ring Road, Mohammadpur, Dhaka': 546,
 'Block E, Kaderabad Housing Society, Bosila, Mohammadpur, Dhaka': 207,
 'Block G, South Banasree Project, Banasree, Dhaka': 234,
 'Jatra Bari, Dhaka': 366,
 'Block L, Eastern Housing, Pallabi, Mirpur, Dhaka': 261,
 'Block J, South Banasree Project, Banasree, Dhaka': 251,
 'Old Eskaton, Eskaton, Dhaka': 517,
 'West Nakhalpara, Tejgaon, Dhaka': 719,
 'Kazirgaon, Jatra Bari, Dhaka': 397,
 'Shiddheswari, Dhaka': 626,
 'Majed Sardar Road, Bangshal, Dhaka': 424,
 'Block B, Dolipara, Uttara, Dhaka': 115,
 'Malibagh Chowdhury Para, Malibagh, Dhaka': 426,
 'South Badda, Badda, Dhaka': 639,
 'Road No 17, Sector 12, Uttara, Dhaka': 554,
 'Rajarbagh, Motijheel, Dhaka': 540,
 'Block C, Dhaka Uddan, Mohammadpur, Dhaka': 148,
 'Paribagh, Dhaka': 526,
 'Joar Sahara, Dhaka': 371,
 'Block D, Niketan, Dhaka': 188,
 'Block B, Section 13, Mirpur, Dhaka': 133,
 'West Nurer Chala, Nurer Chala, Badda, Dhaka': 721,
 'Sultanganj, Rayer Bazaar, Hazaribag, Dhaka': 663,
 'Block A, Section 12, Mirpur, Dhaka': 99,
 'Ashkona, Dakshin Khan, Dhaka': 24,
 'Katashur, Mohammadpur, Dhaka': 392,
 'Block D Extension, Banasree, Dhaka': 168,
 'Adabor, Dhaka': 9,
 'Rayer Bazaar, Hazaribag, Dhaka': 545,
 'Road No 12, Sector 4, Uttara, Dhaka': 552,
 'Block A, Pallabi, Mirpur, Dhaka': 91,
 'Nikunja 1, Nikunja, Dhaka': 490,
 'Block G, Banasree, Dhaka': 229,
 'Aftab Nagar, Dhaka': 12,
 'Maniknagar, Dhaka': 429,
 'Mugdapara, Dhaka': 471,
 'Block M, Banasree, Dhaka': 263,
 'Block L, South Banasree Project, Banasree, Dhaka': 262,
 'Mastertek, Cantonment, Dhaka': 432,
 'North Kamlapur, Kamlapur, Motijheel, Dhaka': 506,
 'Rupnagar R/A, Mirpur, Dhaka': 565,
 'Block K, South Banasree Project, Banasree, Dhaka': 256,
 'Block D, Nobodoy Housing Society, Mohammadpur, Dhaka': 189,
 'Block D, Chandrima Model Town, Mohammadpur, Dhaka': 176,
 'Suchona Model Town, Bochila, Mohammadpur, Dhaka': 661,
 'Block A, Bochila City Developers Ltd, Bochila, Mohammadpur, Dhaka': 74,
 'North Ibrahimpur, Ibrahimpur, Dhaka': 503,
 'Block B, Arambag Residential Area, Pallabi, Mirpur, Dhaka': 105,
 'Shah Ali Bag, Section 1, Mirpur, Dhaka': 609,
 'Block F, Eastern Housing, Pallabi, Mirpur, Dhaka': 222,
 'Sector 1, Block G, Aftab Nagar, Dhaka': 587,
 'North Jatra Bari, Jatra Bari, Dhaka': 504,
 'West Kafrul, Taltola, Agargaon, Dhaka': 709,
 'Block A, Bochila Garden City, Bochila, Mohammadpur, Dhaka': 75,
 'Nazimuddin Road, Saat Rawza, Bangshal, Dhaka': 486,
 'Lake View Society, South Pirerbag, Pirerbag, Mirpur, Dhaka': 410,
 'Sheikhdi, Jatra Bari, Dhaka': 623,
 'Sector 1, Block E, Aftab Nagar, Dhaka': 585,
 'Kamal Soroni, Middle Pirerbag, Pirerbag, Mirpur, Dhaka': 387,
 'Block C, Mansurabad Housing Society, Adabor, Dhaka': 153,
 'Block D, Dhaka Uddan, Mohammadpur, Dhaka': 178,
 'North Shahjahanpur, Dhaka': 511,
 'Block B, Chandrima Model Town, Mohammadpur, Dhaka': 112,
 'East Monipur, Mirpur, Dhaka': 316,
 'Talertek, Khilkhet, Dhaka': 669,
 'Block C, Khilgaon, Dhaka': 152,
 'Vhatara Road, Natun Bazar, Badda, Dhaka': 698,
 'Bibir Bagicha, Jatra Bari, Dhaka': 67,
 'South Mollartek, Dakshin Khan, Dhaka': 655,
 'West Mollartek, Dakshin Khan, Dhaka': 717,
 'Latif Real Estate, Katashur, Mohammadpur, Dhaka': 416,
 'Block A, Dhaka Uddan, Mohammadpur, Dhaka': 80,
 'Matuail, Demra, Dhaka': 435,
 'Jahuri Moholla, Mohammadpur, Dhaka': 359,
 'Arambagh, Motijheel, Dhaka': 21,
 'Shyamoli Housing (2nd Project), Adabor, Dhaka': 630,
 'Nabi Nagar Housing, Mohammadpur, Dhaka': 473,
 'Dhaka Uddan, Mohammadpur, Dhaka': 295,
 'Bochila Garden City, Bochila, Mohammadpur, Dhaka': 270,
 'Block C, Banasree, Dhaka': 140,
 'Avenue 3, Block B, Section 11, Mirpur, Dhaka': 37,
 'North Azampur, Dakshin Khan, Dhaka': 495,
 'Moushair, Dakshin Khan, Dhaka': 469,
 'Block E, South Banasree Project, Banasree, Dhaka': 215,
 'Block F, South Banasree Project, Banasree, Dhaka': 227,
 'South Kallyanpur, Kallyanpur, Mirpur, Dhaka': 649,
 'Zafrabad, Hazaribag, Dhaka': 727,
 'Bochila, Mohammadpur, Dhaka': 271,
 'Turag, Dhaka': 688,
 'Block C, Section 10, Mirpur, Dhaka': 159,
 'Section 15, Mirpur, Dhaka': 580,
 'Sobhanbagh, Tejgaon, Dhaka': 635,
 'East Nakhalpara, Tejgaon, Dhaka': 317,
 'Avenue 11, Mirpur DOHS, Mirpur, Dhaka': 28,
 'Matikata, Cantonment, Dhaka': 434,
 '2nd Colony, Mirpur, Dhaka': 2,
 'Block B, Dhaka Uddan, Mohammadpur, Dhaka': 114,
 'Vashantek, Cantonment, Dhaka': 696,
 'Janata Housing, Sher- E- Banglanagar, West Agargaon, Agargaon, Dhaka': 364,
 'Dakkhin Paikpara, Mirpur, Dhaka': 290,
 'Natun Bazar, Badda, Dhaka': 478,
 'Lalbagh, Dhaka': 412,
 'Bonolota Abashik Elaka, West Agargaon, Agargaon, Dhaka': 273,
 'Road No 11, Block C, Section 11, Mirpur, Dhaka': 550,
 'Tilpapara Road, Tilpapara, Khilgaon, Dhaka': 682,
 'Block D, Section 15, Mirpur, Dhaka': 195,
 'Block C, South Banasree Project, Banasree, Dhaka': 165,
 'Block B, Section 1, Mirpur, Dhaka': 129,
 'Moneshwar, Hazaribag, Dhaka': 465,
 'Old Elephant Road, Maghbazar, Dhaka': 516,
 'Mazar Road, 2nd Colony, Mirpur, Dhaka': 437,
 'Janata Housing, Shah Ali Bag, Section 1, Mirpur, Dhaka': 363,
 'West Agargaon, Agargaon, Dhaka': 704,
 'Tali office Road, Hazaribag, Dhaka': 670,
 'South Maniknagar, Maniknagar, Dhaka': 653,
 'Block F, Section 1, Mirpur, Dhaka': 224,
 'Block B, Bochila City Developers Ltd, Bochila, Mohammadpur, Dhaka': 108,
 'Block E, Section 1, Mirpur, Dhaka': 210,
 'Shimulbag, West Rampura, Rampura, Dhaka': 627,
 'Block B, Bochila West Dhanmondi R/A, Bochila, Mohammadpur, Dhaka': 110,
 'Indira Road, Tejgaon, Dhaka': 356,
 'Block C, Eastern Housing, Pallabi, Mirpur, Dhaka': 149,
 'Golapbag, Jatra Bari, Dhaka': 337,
 'Block A, Section 1, Mirpur, Dhaka': 96,
 'Block A, Sayednagar, East Vatara, Vatara, Badda, Dhaka': 95,
 'Block E, Eastern Housing, Pallabi, Mirpur, Dhaka': 206,
 'Block D, Pallabi, Mirpur, Dhaka': 190,
 'Begum Bazar, Bangshal, Dhaka': 64,
 'Vatara, Badda, Dhaka': 697,
 'Sadarghat, Kotwali, Dhaka': 569,
 'South Manikdi, Manikdi, Cantonment, Dhaka': 652,
 'North Kalachandpur, Kalachandpur, Dhaka': 505,
 'Middle Bashabo, Bashabo, Dhaka': 441,
 'Block C, Chandrima Model Town, Mohammadpur, Dhaka': 146,
 'North Goran, Goran, Khilgaon, Dhaka': 500,
 'Sankar, Hazaribag, Dhaka': 570,
 'Hashem Khan Road, Sultanganj, Rayer Bazaar, Hazaribag, Dhaka': 347,
 'Block B, Section 2, Mirpur, Dhaka': 134,
 'Sonatangar, Jigatola, Hazaribag, Dhaka': 637,
 'Boshoty Housing, Borobag, Section 2, Mirpur, Dhaka': 276,
 'Swapnodhara Housing, Bochila, Mohammadpur, Dhaka': 666,
 'Sikder Real Estate, Tali office Road, Hazaribag, Dhaka': 633,
 'Abur Tek, Khilkhet, Dhaka': 8,
 'Fakirapool, Motijheel, Dhaka': 327,
 'North Bashabo, Bashabo, Dhaka': 496,
 'Block E, Arambag Residential Area, Pallabi, Mirpur, Dhaka': 201,
 'Shahidbag, Malibagh, Dhaka': 612,
 'Block C, Arambag Residential Area, Pallabi, Mirpur, Dhaka': 139,
 'Arambag Residential Area, Mirpur, Dhaka': 19,
 'West Katashur, Katashur, Mohammadpur, Dhaka': 712,
 'Bashabo, Dhaka': 61,
 'Purbanchal Road, Uttar Badda, Badda, Dhaka': 536,
 'West Maniknagar, Maniknagar, Dhaka': 715,
 'Katabon, New Market, Dhaka': 391,
 'Shahjahanpur, Dhaka': 614,
 'Bonobithi Abashik Alaka, East Azampur, Dakshin Khan, Dhaka': 272,
 'Bot Tola, Khilkhet, Dhaka': 278,
 'Block J, Eastern Housing, Pallabi, Mirpur, Dhaka': 248,
 'Naddapara, Dakshin Khan, Dhaka': 475,
 'East Namapara, Namapara, Khilkhet, Dhaka': 318,
 'Purana Paltan, Motijheel, Dhaka': 534,
 'Ahmed Nagar, Mirpur, Dhaka': 14,
 'Kamlapur, Motijheel, Dhaka': 389,
 'Shamibag Road, Shamibag, Sutrapur, Dhaka': 616,
 'Uttar Para, Khilkhet, Dhaka': 694,
 'Block G/1, Section 2, Mirpur, Dhaka': 235,
 'North Donia, Donia, Jatra Bari, Dhaka': 498,
 'Eastern Pallabi, Pallabi, Mirpur, Dhaka': 323,
 'South Mugdapara, Mugdapara, Dhaka': 657,
 'Sector 1, Block D, Aftab Nagar, Dhaka': 584,
 'Naya Nagar, Khilkhet, Dhaka': 481,
 'Block B, Section 10, Mirpur, Dhaka': 130,
 'Kadamtala Road, Kadamtala, Bashabo, Dhaka': 374,
 'Block A, Section 6, Mirpur, Dhaka': 102,
 'Chawk Bazar, Lalbagh, Dhaka': 285,
 'Bagan Bari, Cantonment, Dhaka': 48,
 'aziz Moholla, Mohammadpur, Dhaka': 728,
 'Sunibir Housing Society, Adabor, Dhaka': 664,
 'Block D, Kaderabad Housing Society, Bosila, Mohammadpur, Dhaka': 182,
 'South Madartek, Madartek, Bashabo, Dhaka': 651,
 'Chayabithi Eastern Housing, Middle Bashabo, Bashabo, Dhaka': 286,
 'Kawlar, Dakshin Khan, Dhaka': 395,
 'Matikata Bazar Road, Matikata, Cantonment, Dhaka': 433,
 'Popular Housing, Borobag, Section 2, Mirpur, Dhaka': 531,
 'South Azampur, Dakshin Khan, Dhaka': 638,
 'Nobinbagh, West Meradia, Meradia, Khilgaon, Dhaka': 492,
 '22 Bari, West Kazipara, Mirpur, Dhaka': 1,
 'Sipahibagh, North Goran, Goran, Khilgaon, Dhaka': 634,
 'Block Ka, Section 6, Mirpur, Dhaka': 258,
 'Bosila, Mohammadpur, Dhaka': 277,
 'Block A, Arifabad Housing Society, Pallabi, Mirpur, Dhaka': 71,
 'Jurain, Shyampur, Dhaka': 372,
 'Block C, Chad Uddan Housing, Mohammadpur, Dhaka': 144,
 'Block B, Chad Uddan Housing, Mohammadpur, Dhaka': 111,
 'Jashimuddin Avenue, Dolipara, Uttara, Dhaka': 365,
 'Block D, Dakkhin Paikpara, Paikpara, Mirpur, Dhaka': 177,
 'Block D, Banasree, Dhaka': 172,
 'Block H, Section 2, Mirpur, Dhaka': 240,
 'Paikpara, Mirpur, Dhaka': 521,
 'Aainusbag, Dakshin Khan, Dhaka': 5,
 'West Meradia, Meradia, Khilgaon, Dhaka': 716,
 'Block C, Section 6, Mirpur, Dhaka': 164,
 'Bijoy Nagar, Purana Paltan, Motijheel, Dhaka': 68,
 'Avenue 2, Block C, Section 13, Mirpur, Dhaka': 32,
 'Narinda, Sutrapur, Dhaka': 477,
 'Armanitola, Naya Bazar, Bangshal, Dhaka': 23,
 'Avenue 3, Block A, Section 11, Mirpur, Dhaka': 36,
 'Khilbari Tek, Badda, Dhaka': 401,
 'Mukti Polli, Khilbari Tek, Badda, Dhaka': 472,
 'Purana Polton Lane, Purana Paltan, Motijheel, Dhaka': 535,
 'Adarsha Nagar, Badda, Dhaka': 10,
 'Polashpur, East Doniya, Doniya, Shyampur, Dhaka': 530,
 'Block D, Bochila Garden City, Bochila, Mohammadpur, Dhaka': 174,
 'Jagannathpur, Badda, Dhaka': 358,
 'Road No 18/A, Block E, Bashundhara R-A, Dhaka': 555,
 'Adarsha Para, Uttar Khan, Dhaka': 11,
 'Block C Extension, Banasree, Dhaka': 137,
 'Tallabag, Hazaribag, Dhaka': 671,
 'Shantipur, South Goran, Goran, Khilgaon, Dhaka': 620,
 'Block B, Section 6, Mirpur, Dhaka': 135,
 'Sector 2, Block D, Aftab Nagar, Dhaka': 596,
 'Bakshi Bazar, Lalbagh, Dhaka': 52,
 'Block C, Section 1, Mirpur, Dhaka': 158,
 'Block B, Kaderabad Housing Society, Bosila, Mohammadpur, Dhaka': 118,
 'Madartek, Bashabo, Dhaka': 419,
 'Shadhinata Sharani, Uttar Badda, Badda, Dhaka': 608,
 'Block J, Pallabi Extension, Pallabi, Mirpur, Dhaka': 249,
 'North Pirerbag, Pirerbag, Section 1, Mirpur, Dhaka': 510,
 'Gudaraghat, Middle Badda, Badda, Dhaka': 343,
 'Block D, Section 1, Mirpur, Dhaka': 191,
 'Block A, Bochila West Dhanmondi R/A, Bochila, Mohammadpur, Dhaka': 76,
 'Block C, Metro Housing, Bochila, Mohammadpur, Dhaka': 154,
 'Janata Housing Society, Adabor, Dhaka': 362,
 'Section 13, Mirpur, Dhaka': 579,
 'Block A, Section 13, Mirpur, Dhaka': 100,
 'TIC Colony, Faydabad, Dakshin Khan, Dhaka': 667,
 'Turag City, Section 1, Mirpur, Dhaka': 686,
 'Moushan East Para, Kuril, Dhaka': 470,
 'Block D, Section 6, Mirpur, Dhaka': 197,
 'East Hazipara, East Rampura, Rampura, Dhaka': 308,
 'Block A, Arambag Residential Area, Pallabi, Mirpur, Dhaka': 70,
 'Avenue 2, Block A, Section 13, Mirpur, Dhaka': 31,
 'Darussalam, Mirpur, Dhaka': 293,
 'West Dhanmondi, Dhanmondi, Dhaka': 706,
 'Road No 12, Block B, Section 11, Mirpur, Dhaka': 551,
 'Block D, Arambag Residential Area, Pallabi, Mirpur, Dhaka': 170,
 'Sector 2, Block E, Aftab Nagar, Dhaka': 597,
 'Mannan Sharani, West Shewrapara, Mirpur, Dhaka': 430,
 'Road No 9, Block A, Section 11, Mirpur, Dhaka': 562,
 'Abdullahbag, Uttar Badda, Badda, Dhaka': 6,
 'Bangshal, Dhaka': 57,
 'Block B, Pallabi, Mirpur, Dhaka': 127,
 'Bhagalpur, Hazaribag, Dhaka': 65,
 'Malibag Bazar Rd, Malibagh, Dhaka': 425,
 'Jamtola, Kawlar, Dakshin Khan, Dhaka': 361,
 'Kawlar Moddho Para, Kawlar, Dakshin Khan, Dhaka': 394,
 'Shardar Bari, Dakshin Khan, Dhaka': 621,
 'Abdur Rafique Housing Society, Shekhertek, Mohammadpur, Dhaka': 7,
 'Khaje Dewan, Lalbagh, Dhaka': 400,
 'Kellar Mor, Lalbagh, Dhaka': 398,
 'Ali And Nur Real Estate, Mohammadpur, Dhaka': 16,
 'Sayednagar, East Vatara, Vatara, Badda, Dhaka': 573,
 'Lalmati, Block E, Section 11, Mirpur, Dhaka': 414,
 'Tejturi Bazar, Tejgaon, Dhaka': 679,
 'Eastern Housing, Pallabi, Mirpur, Dhaka': 322,
 'Tekpara, Badda, Dhaka': 680,
 'Taltola, Dhaka': 674,
 'Ward 23, Chowdhuripara, Khilgaon, Dhaka': 699,
 'West Nandipara, Khilgaon, Dhaka': 720,
 'Mofizbag Housing, Shekhertek, Mohammadpur, Dhaka': 455,
 'Karwan Bazar, Tejgaon, Dhaka': 390,
 'Jhilpar, Middle Pirerbag, Pirerbag, Mirpur, Dhaka': 369,
 'South Goran, Khilgaon, Dhaka': 647,
 'Block Ka, North Bishil, Section 1, Mirpur, Dhaka': 257,
 'Block Cha, Section 2, Mirpur, Dhaka': 167,
 'Block TA, Section 6, Mirpur, Dhaka': 268,
 'Moddo Para, Khilkhet, Dhaka': 453,
 'Block E, Niketan, Dhaka': 209,
 'Chalabon, Dakshin Khan, Dhaka': 282,
 'Green Road, Dhanmondi, Dhaka': 342,
 'Block B, Future Town, Bochila, Mohammadpur, Dhaka': 117,
 'Block TA, Section 12, Mirpur, Dhaka': 267,
 'Nawabgonj, Lalbagh, Dhaka': 479,
 'Sutrapur, Dhaka': 665,
 'Sepahibag, North Goran, Khilgaon, Dhaka-1219, Goran, Khilgaon, Dhaka': 607,
 'Sher- E- Banglanagar, West Agargaon, Agargaon, Dhaka': 624,
 'North Vashantek, Vashantek, Cantonment, Dhaka': 513,
 'East Manikdi, Manikdi, Cantonment, Dhaka': 312,
 'Chairman Para, Dakshin Khan, Dhaka': 281,
 'South Bishil, Section 1, Mirpur, Dhaka': 643,
 'North Shahjahanpur, Shahjahanpur, Dhaka': 512,
 'PC Culture Housing Society, Shyamoli, Dhaka': 518,
 'Mirpur Road, New Market, Dhaka': 450,
 'Block A, Mansurabad Housing Society, Adabor, Dhaka': 86,
 'Block B, Sayednagar, East Vatara, Vatara, Badda, Dhaka': 128,
 'Arifabad Housing Society, Pallabi, Mirpur, Dhaka': 22,
 'South Shahjahanpur, Shahjahanpur, Dhaka': 660,
 'Block D, Dolipara, Uttara, Dhaka': 179,
 'Block B, Notunbag, Taltola, Khilgaon, Dhaka': 126,
 'East Azampur, Dakshin Khan, Dhaka': 304,
 '3rd Colony, Mirpur, Dhaka': 4,
 'Block C, Bochila Garden City, Bochila, Mohammadpur, Dhaka': 143,
 'Luxmibazar, Sutrapur, Dhaka': 417,
 'Saat Rawza, Bangshal, Dhaka': 566,
 'West Pirerbag, Pirerbag, Mirpur, Dhaka': 722,
 'Avenue 2, Block A, Section 11, Mirpur, Dhaka': 30,
 'Shamibag, Sutrapur, Dhaka': 617,
 'Block E, Arifabad Housing Society, Pallabi, Mirpur, Dhaka': 202,
 'West Kafrul, Taltola, Dhaka': 710,
 'Porod Diea, Satarkul, Uttar Badda, Badda, Dhaka': 532,
 'North Goran, Khilgaon, Goran, Khilgaon, Dhaka': 502,
 'Pilkhana, Hazaribag, Dhaka': 527,
 'Moddhopara, Ashkona, Dakshin Khan, Dhaka': 452,
 'Lalkuthi, 3rd Colony, Mirpur, Dhaka': 413,
 'East Mollartek, Dakshin Khan, Dhaka': 315,
 'IBN SINA Housing, Adabor, Dhaka': 354,
 'Block F, Mohammadpur, Dhaka': 223,
 'Block E, Chandrima Model Town, Mohammadpur, Dhaka': 205,
 'Block H, South Banasree Project, Banasree, Dhaka': 241,
 'Block B, Metro Housing, Bochila, Mohammadpur, Dhaka': 121,
 'North Adabor, Adabor, Dhaka': 494,
 'Faydabad, East Azampur, Dakshin Khan, Dhaka': 330,
 'Mansurabad Housing Society, Adabor, Dhaka': 431,
 'Block B, Mohanagar Housing, West Rampura, Rampura, Dhaka': 123,
 'Block C, Mohanagar Housing, West Rampura, Rampura, Dhaka': 155,
 'Jagannath Shaha Road, Amligola, Lalbagh, Dhaka': 357,
 'Uttar Khan, Dhaka': 692,
 'North Goran, Khilgaon, Dhaka': 501,
 'Avenue 8, Mirpur DOHS, Mirpur, Dhaka': 44,
 'Avenue 12, Mirpur DOHS, Mirpur, Dhaka': 29,
 'Baithakali, Badda, Dhaka': 50,
 'Lalbagh Road, Lalbagh, Dhaka': 411,
 'East Khilbari Tek, Khilbari Tek, Badda, Dhaka': 310,
 'Block A, Metro Housing, Bochila, Mohammadpur, Dhaka': 87,
 'Nayatola, Boro Maghbazar, Maghbazar, Dhaka': 484,
 'Block B, Eastern Housing, Pallabi, Mirpur, Dhaka': 116,
 'Mohanagar Housing, West Rampura, Rampura, Dhaka': 462,
 'Uttar Namapara, Namapara, Khilkhet, Dhaka': 693,
 'Anurbag, Dakshin Khan, Dhaka': 18,
 'Green City Housing, Mohammadpur, Dhaka': 341,
 'Sujat Nagar, Pallabi, Mirpur, Dhaka': 662,
 'Block C, Future Town, Bochila, Mohammadpur, Dhaka': 150,
 'Block F, Aftab Nagar, Dhaka': 217,
 'Barontek, Cantonment, Dhaka': 60,
 'Avenue 5, Mirpur DOHS, Mirpur, Dhaka': 41,
 'South Bashabo, Bashabo, Dhaka': 642,
 'Nowapara, Dakshin Khan, Dhaka': 514,
 'Sabujbag, South Bashabo, Bashabo, Dhaka': 567,
 'Taltola, Dakshin Khan, Dhaka': 673,
 'Sadarghat, Dhaka': 568,
 'Block F, Arambag Residential Area, Pallabi, Mirpur, Dhaka': 218,
 'Block C, Chandmiya Housing, Mohammadpur, Dhaka': 145,
 'Donia, Jatra Bari, Dhaka': 300,
 'Kotwali, Dhaka': 405,
 'Rupali Housing, Section 3, Mirpur, Dhaka': 564,
 'Avenue 2A, Mirpur DOHS, Mirpur, Dhaka': 35,
 'Section 11, Mirpur, Dhaka': 577,
 'Turag Housing, Mohammadpur, Dhaka': 687,
 'South Matuail, Matuail, Demra, Dhaka': 654,
 'North Mugdapara, Mugdapara, Dhaka': 508,
 'Ray Shaheb Bazar, Sutrapur, Dhaka': 544,
 'West Vatara, Vatara, Badda, Dhaka': 725,
 'Block A, South Banasree Project, Banasree, Dhaka': 103,
 'Block G, Section 2, Mirpur, Dhaka': 233,
 'Avenue 10, Mirpur DOHS, Mirpur, Dhaka': 27,
 'Block C, Niketan, Dhaka': 156,
 'Naya Nagar, Vatara, Badda, Dhaka': 482,
 'Mahuthtuli, Bangshal, Dhaka': 423,
 'Sector 15, Uttara, Dhaka': 595,
 'Avenue 7, Mirpur DOHS, Mirpur, Dhaka': 43,
 'Block B, Mohammadi Homes R/A, Mohammadpur, Dhaka': 122,
 'Block E, Section 6, Mirpur, Dhaka': 214,
 'Bou Bazar, East Hazipara, East Rampura, Rampura, Dhaka': 279,
 'Block B, Bochila Garden City, Bochila, Mohammadpur, Dhaka': 109,
 'Mayakanon, Sabujbag, South Bashabo, Bashabo, Dhaka': 436,
 'Block C, Dakkhin Paikpara, Paikpara, Mirpur, Dhaka': 147,
 'Rajarbag, Bashabo, Dhaka': 539,
 'Goaltek, Dakshin Khan, Dhaka': 334,
 'Kazibari, Dakshin Khan, Dhaka': 396,
 'Block F, Dhaka Uddan, Mohammadpur, Dhaka': 221,
 'Goaltek, Faydabad, Dakshin Khan, Dhaka': 335,
 'Road No 8, Block A, Section 11, Mirpur, Dhaka': 561,
 'Nobodoy Housing Society, Mohammadpur, Dhaka': 493,
 'Borobag, Section 2, Mirpur, Dhaka': 275,
 'Ring Road, Shyamoli, Dhaka': 547,
 'Hazipara, Dakshin Khan, Dhaka': 353,
 'East Madartek, Madartek, Bashabo, Dhaka': 311,
 'Block B, Kaderabad Housing Society, Katashur, Mohammadpur, Dhaka': 119,
 'Monipur, Mirpur, Dhaka': 466,
 'Kaderabad Housing Society, Bosila, Mohammadpur, Dhaka': 376,
 'Ward 6, West Nurer Chala, Nurer Chala, Badda, Dhaka': 700,
 'Block D, Chad Uddan Housing, Mohammadpur, Dhaka': 175,
 'Naya Bazar, Bangshal, Dhaka': 480,
 'Block G, Eastern Housing, Pallabi, Mirpur, Dhaka': 231,
 'Block H, Aftab Nagar, Dhaka': 236,
 'Solmaid, Badda, Dhaka': 636,
 'Avenue 2, Section 11, Mirpur, Dhaka': 34,
 'Ward 9, East Khilbari Tek, Khilbari Tek, Badda, Dhaka': 701,
 'Block A, Kaderabad Housing Society, Katashur, Mohammadpur, Dhaka': 84,
 'Golartek, Section 1, Mirpur, Dhaka': 338,
 'Block D, Metro Housing, Bochila, Mohammadpur, Dhaka': 186,
 'Kuratoli, Kuril, Dhaka': 407,
 'Banglamotors, Dhaka': 56,
 'North Manikdi, Manikdi, Cantonment, Dhaka': 507,
 'Duip R-A, Block A, Section 2, Mirpur, Dhaka': 301,
 'Block A, Future Town, Bochila, Mohammadpur, Dhaka': 82,
 'Block E, Section 11, Mirpur, Dhaka': 211,
 'Block J, Section 3, Mirpur, Dhaka': 250,
 'Block New C, Section 1, Mirpur, Dhaka': 266,
 'Block D, Future Town, Bochila, Mohammadpur, Dhaka': 181,
 'Madartek, East Bashabo, Bashabo, Dhaka': 420,
 'Faidabad Garden City, Faydabad, Dakshin Khan, Dhaka': 326,
 'Elephant Road, New Market, Dhaka': 324,
 'Pakar Matha, East Shewrapara, Mirpur, Dhaka': 522,
 'Transmitter, Faydabad, Dakshin Khan, Dhaka': 685,
 'Block A, Eastern Housing, Pallabi, Mirpur, Dhaka': 81,
 'Block B, Dakkhin Paikpara, Paikpara, Mirpur, Dhaka': 113,
 'South Kutubkhali, Kutubkhali, Jatra Bari, Dhaka': 650,
 'Pirerbag, Section 1, Mirpur, Dhaka': 529,
 'West Jatrabari, Jatra Bari, Dhaka': 708,
 'Sayedabad, Jatra Bari, Dhaka': 572,
 'Kalibari, Rajarbag, Bashabo, Dhaka': 384,
 'Shuritola, Bangshal, Dhaka': 629,
 'Future Town, Bochila, Mohammadpur, Dhaka': 331,
 'Mir Hajirbag, Jatra Bari, Dhaka': 448,
 'Block H, Kazi Furi, Ghudaraghat, Section 1, Mirpur, Dhaka': 239,
 'Chandrima Model Town, Mohammadpur, Dhaka': 284,
 'Kahektuli, Bangshal, Dhaka': 379,
 'Ward 98, Rampura, Dhaka': 702,
 'Block Kha, North Bishil, Section 1, Mirpur, Dhaka': 259,
 'Atish Deepankar Road, Bashabo, Dhaka': 25,
 'Akota Residential Area, Uttar Badda, Badda, Dhaka': 15,
 'Arambag Residential Area, Pallabi, Mirpur, Dhaka': 20,
 'Zafrabad, Dhaka': 726,
 'Block D2, Section 10, Mirpur, Dhaka': 199,
 'Block A, Rainkhola, Section 2, Mirpur, Dhaka': 92,
 'Bawaila Para, Badda, Dhaka': 63,
 'West Dolairpar, Shyampur, Dhaka': 707,
 'Block C, Section 11, Mirpur, Dhaka': 160,
 'Bhuiya Estate, Jhauchor, Hazaribag, Dhaka': 66,
 'Middle Kuril, Kuril, Dhaka': 443,
 'Rasulpur, Donia, Jatra Bari, Dhaka': 543,
 'Goltek, Cantonment, Dhaka': 339,
 'Kutubkhali, Jatra Bari, Dhaka': 409,
 'Block D, Aftab Nagar, Dhaka': 169,
 'Road No 1, West Nandipara, Khilgaon, Dhaka': 548,
 'Section 3, Mirpur, Dhaka': 582,
 'Dhorangartek, Turag, Dhaka': 297,
 'Block C1, Sector 15, Uttara, Dhaka': 166,
 'Block K, Eastern Housing, Pallabi, Mirpur, Dhaka': 255,
 'East Ahmed Nagar, Ahmed Nagar, Mirpur, Dhaka': 303,
 'Duip R-A, Block B, Section 2, Mirpur, Dhaka': 302,
 'Block D, Kaderabad Housing Society, Katashur, Mohammadpur, Dhaka': 183,
 'Jhigatola Road, Dhanmondi, Dhaka': 368,
 'Block A, Chandmiya Housing, Mohammadpur, Dhaka': 78,
 'Hazaribagh Road, Hazaribag, Dhaka': 352,
 'Road No 2, Block D, Bashundhara R-A, Dhaka': 556,
 'Konapara, Demra, Dhaka': 404,
 'Gojmohal, Hazaribag, Dhaka': 336,
 'Sayem Sobhan Anvir Road, Block C, Bashundhara R-A, Dhaka': 574,
 'South Pirerbag, Pirerbag, Section 1, Mirpur, Dhaka': 659,
 'East Rasulpur, Rasulpur, Donia, Jatra Bari, Dhaka': 320,
 'Block I, Arifabad Housing Society, Pallabi, Mirpur, Dhaka': 243,
 'Hazaribag Model Town, Hazaribag, Dhaka': 350,
 'Sector 1, Block K, Aftab Nagar, Dhaka': 588,
 'Block K, Aftab Nagar, Dhaka': 252,
 'Road No 5, Dhanmondi, Dhaka': 558,
 'Sher-E-Bangla Avenue, Dolipara, Uttara, Dhaka': 625,
 'Ranavola- Block D, Sector 10, Uttara, Dhaka': 542,
 'Block D, Arifabad Housing Society, Pallabi, Mirpur, Dhaka': 171,
 'Mir Hajir Bag Road, West Dolairpar, Shyampur, Dhaka': 447,
 'Kulutala, Sutrapur, Dhaka': 406,
 'Shaikh Saheb Bazar Road, Azimpur, Lalbagh, Dhaka': 615,
 'Jhauchor, Hazaribag, Dhaka': 367,
 'Block E1, Chandrima Model Town, Mohammadpur, Dhaka': 216,
 'South Jatra Bari, Jatra Bari, Dhaka': 648,
 'Madani Avenue, Natun Bazar, Badda, Dhaka': 418,
 'Block N, South Banasree Project, Banasree, Dhaka': 265,
 'North Bishil, Section 1, Mirpur, Dhaka': 497,
 'Middle Faydabad, Faydabad, Dakshin Khan, Dhaka': 442,
 'Hatimbag, Dakshin Khan, Dhaka': 348,
 'Mohammadi Homes R/A, Mohammadpur, Dhaka': 458,
 'Panthapath, Kathalbagan, Dhaka': 525,
 'Tati Bazaar, Kotwali, Dhaka': 676,
 'Chowdhury Bazar, Lalbagh, Dhaka': 288,
 'Keraniganj, Dhaka': 399}

# Create your views here.
def home(request):
    return render(request, 'App_all/home.html')

def features(request):
    content = {
        'all_locations': location_dictionary.keys(),
    }
    return render(request, 'App_all/features.html', context=content)

food_model = 'App_all/main_model/food_model_rfr.pkl'
with open(food_model, 'rb') as file:
    food_costing_model = pickle.load(file)
house_model = 'App_all/main_model/house_rent_model.pkl'
with open(house_model, 'rb') as file:
    house_loaded_model = pickle.load(file)

def predict_view(request):
    if request.method == 'POST':
        apatment_size = request.POST.get('apatment_size')
        no_of_bed = request.POST.get('no_of_bed')
        no_of_bath = request.POST.get('no_of_bath')
        height = request.POST.getlist('height')
        weight = request.POST.getlist('weight')
        location = request.POST.get('selected_location')
        area_code = location_dictionary[location]
        bmi = []
        food_need = []
        for i, j in zip(height, weight):
            the_bmi = float(j) / (float(i)/100) ** 2
            prediction = food_costing_model.predict([[the_bmi]])
            food_need.append(prediction[0])
        house_price_ = house_loaded_model.predict([[int(apatment_size), int(no_of_bed), int(no_of_bath), int(area_code)]])
        print(house_price_)
        total_food_cost = sum(food_need)
        total_house_cost = house_price_[0]
        total_cost = total_food_cost + total_house_cost
        content = {
            'apatment_size': apatment_size,
            'no_of_bed': no_of_bed,
            'no_of_bath': no_of_bath,
            'height': height,
            'weight': weight,
            'location': location,
            'area_code': area_code,
            'bmi': bmi,
            'food_need': food_need,
            'house_price_': house_price_,
            'total_food_cost': total_food_cost,
            'total_house_cost': total_house_cost,
            'total_cost': total_cost,
        }
        return HttpResponse("<h1>Your total cost will be approximately: ৳ " + str(floor(total_cost)) +"</h1>")
    return HttpResponse("Hello, world. You're at the predict_view.")


def contact_us(request):
    return render(request, 'App_all/contact.html')
